# Cloud Build config to build and deploy bloocube-admin to Cloud Run
# Configure your Cloud Build trigger to use this file and set substitutions.
# Required substitutions:
#  _REGION: e.g. us-central1
#  _SERVICE: bloocube-adminwafinwaf
#  _ADMIN_API_URL: e.g. https://your-backend-host

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/${_SERVICE}:$SHORT_SHA", "-f", "bloocube-admin/Dockerfile", "bloocube-admin"]

  - name: gcr.io/cloud-builders/docker
    args: ["push", "gcr.io/$PROJECT_ID/${_SERVICE}:$SHORT_SHA"]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "${_SERVICE}",
        "--image", "gcr.io/$PROJECT_ID/${_SERVICE}:$SHORT_SHA",
        "--region", "${_REGION}",
        "--platform", "managed",
        "--allow-unauthenticated",
        "--port", "8080",
        "--set-env-vars", "NODE_ENV=production",
        "--set-env-vars", "NEXT_PUBLIC_ADMIN_API_URL=${NEXT_PUBLIC_ADMIN_API_URL}"
      ]

images:
  - gcr.io/$PROJECT_ID/${_SERVICE}:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
