# Cloud Build config to build and deploy bloocube-admin to Cloud Run

steps:
  # Build the Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t", "asia-southeast1-docker.pkg.dev/$PROJECT_ID/bloocube/bloocube-admin:latest",
        "-f", "bloocube-admin/Dockerfile",
        "--build-arg", "NEXT_PUBLIC_ADMIN_API_URL=https://api-backend.bloocube.com",
        "bloocube-admin"
      ]

  # Push the image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args: ["push", "asia-southeast1-docker.pkg.dev/$PROJECT_ID/bloocube/bloocube-admin:latest"]

  # Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "bloocube-admin",
        "--image", "asia-southeast1-docker.pkg.dev/$PROJECT_ID/bloocube/bloocube-admin:latest",
        "--region", "asia-southeast1",
        "--platform", "managed",
        "--allow-unauthenticated",
        "--port", "8080",
        "--memory", "512Mi",
        "--cpu", "1",
        "--timeout", "300",
        "--set-env-vars", "NODE_ENV=production,NEXT_PUBLIC_ADMIN_API_URL=https://api-backend.bloocube.com"
      ]

images:
  - asia-southeast1-docker.pkg.dev/$PROJECT_ID/bloocube/bloocube-admin:latest

options:
  logging: CLOUD_LOGGING_ONLY